### ISSUE TITLE
Error: Unhandled exception executing 'pet llama' in com.dsh105.echopet.commands.util.DynamicPluginCommand(pet)

### ISSUE THREAD

**Issue by Waterman1001** [Arnuh/EchoPet#101]
I am really confused.
When I try to use Llama pet and Slime pet on my Live server, I get the following errors in the logs:

```
[23:54:40] [Server thread/INFO]: waterman1001 issued server command: /pet llama
[23:54:40] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'pet llama' in com.dsh105.echopet.commands.util.DynamicPluginCommand(pet)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:169) ~[patched_1.17.1.jar:git-Paper-112]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:821) ~[patched_1.17.1.jar:git-Paper-112]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2170) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:1981) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:1962) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:6) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:36) ~[?:?]
	at net.minecraft.network.protocol.PlayerConnectionUtils$$Lambda$6999/0x00000000a86c54d8.run(Unknown Source) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Paper-112]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1348) ~[patched_1.17.1.jar:git-Paper-112]
	at net.minecraft.server.MinecraftServer.shouldRun(MinecraftServer.java:190) ~[patched_1.17.1.jar:git-Paper-112]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1327) ~[patched_1.17.1.jar:git-Paper-112]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1320) ~[patched_1.17.1.jar:git-Paper-112]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1281) ~[patched_1.17.1.jar:git-Paper-112]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1192) ~[patched_1.17.1.jar:git-Paper-112]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-112]
	at net.minecraft.server.MinecraftServer$$Lambda$3657/0x0000000045f10478.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.IllegalStateException: Failed to create EntityPet object for waterman1001
	at com.dsh105.echopet.compat.api.registration.PetRegistrationEntry.createEntityPet(PetRegistrationEntry.java:87) ~[?:?]
	at com.dsh105.echopet.compat.api.entity.PetType.getNewEntityPetInstance(PetType.java:234) ~[?:?]
	at com.dsh105.echopet.compat.nms.v1_17_R1.SpawnUtil.spawn(SpawnUtil.java:56) ~[?:?]
	at com.dsh105.echopet.api.pet.Pet.spawnPet(Pet.java:93) ~[?:?]
	at com.dsh105.echopet.commands.PetCommand.onCommand(PetCommand.java:443) ~[?:?]
	at com.dsh105.echopet.commands.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:50) ~[?:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.17.1.jar:git-Paper-112]
	... 22 more
Caused by: java.lang.IllegalArgumentException: argument type mismatch
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:?]
	at com.dsh105.echopet.compat.api.registration.PetRegistrationEntry.createEntityPet(PetRegistrationEntry.java:83) ~[?:?]
	at com.dsh105.echopet.compat.api.entity.PetType.getNewEntityPetInstance(PetType.java:234) ~[?:?]
	at com.dsh105.echopet.compat.nms.v1_17_R1.SpawnUtil.spawn(SpawnUtil.java:56) ~[?:?]
	at com.dsh105.echopet.api.pet.Pet.spawnPet(Pet.java:93) ~[?:?]
	at com.dsh105.echopet.commands.PetCommand.onCommand(PetCommand.java:443) ~[?:?]
	at com.dsh105.echopet.commands.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:50) ~[?:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.17.1.jar:git-Paper-112]
	... 22 more
```

And the one with a Slime:

```
[23:55:10] [Server thread/INFO]: waterman1001 issued server command: /pet slime
[23:55:10] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'pet slime' in com.dsh105.echopet.commands.util.DynamicPluginCommand(pet)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:169) ~[patched_1.17.1.jar:git-Paper-112]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:821) ~[patched_1.17.1.jar:git-Paper-112]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2170) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:1981) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:1962) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:6) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:36) ~[?:?]
	at net.minecraft.network.protocol.PlayerConnectionUtils$$Lambda$6999/0x00000000a86c54d8.run(Unknown Source) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Paper-112]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1348) ~[patched_1.17.1.jar:git-Paper-112]
	at net.minecraft.server.MinecraftServer.shouldRun(MinecraftServer.java:190) ~[patched_1.17.1.jar:git-Paper-112]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1327) ~[patched_1.17.1.jar:git-Paper-112]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1320) ~[patched_1.17.1.jar:git-Paper-112]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1281) ~[patched_1.17.1.jar:git-Paper-112]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1192) ~[patched_1.17.1.jar:git-Paper-112]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-112]
	at net.minecraft.server.MinecraftServer$$Lambda$3657/0x0000000045f10478.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.IllegalStateException: Failed to create EntityPet object for waterman1001
	at com.dsh105.echopet.compat.api.registration.PetRegistrationEntry.createEntityPet(PetRegistrationEntry.java:87) ~[?:?]
	at com.dsh105.echopet.compat.api.entity.PetType.getNewEntityPetInstance(PetType.java:234) ~[?:?]
	at com.dsh105.echopet.compat.nms.v1_17_R1.SpawnUtil.spawn(SpawnUtil.java:56) ~[?:?]
	at com.dsh105.echopet.api.pet.Pet.spawnPet(Pet.java:93) ~[?:?]
	at com.dsh105.echopet.commands.PetCommand.onCommand(PetCommand.java:443) ~[?:?]
	at com.dsh105.echopet.commands.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:50) ~[?:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.17.1.jar:git-Paper-112]
	... 22 more
Caused by: java.lang.IllegalArgumentException: argument type mismatch
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:?]
	at com.dsh105.echopet.compat.api.registration.PetRegistrationEntry.createEntityPet(PetRegistrationEntry.java:83) ~[?:?]
	at com.dsh105.echopet.compat.api.entity.PetType.getNewEntityPetInstance(PetType.java:234) ~[?:?]
	at com.dsh105.echopet.compat.nms.v1_17_R1.SpawnUtil.spawn(SpawnUtil.java:56) ~[?:?]
	at com.dsh105.echopet.api.pet.Pet.spawnPet(Pet.java:93) ~[?:?]
	at com.dsh105.echopet.commands.PetCommand.onCommand(PetCommand.java:443) ~[?:?]
	at com.dsh105.echopet.commands.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:50) ~[?:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.17.1.jar:git-Paper-112]
	... 22 more
```

However, I do _not_ receive these errors when using other mobs, like Foxes.

Even more strange is the following:
I installed the plugin on my test server with similar plugins and the exact same paper version, and I was NOT able to reproduce this.
So there seems to be a difference between my live and testserver still, but I also do not see what this difference could be and moreover, the error does also seem to only belong to Echopet and is non-related to any other plugins.
Would you have any idea how to resolve this issue? Judging from the error logs?
I am so confused right now.

Running: Paper version git-Paper-112 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: bc127ea)
EchoPet version 1.0.8-SNAPSHOT-b29

**Comment by Waterman1001** [comment]
That was fast, thank you so much Arnuh! :)
