### ISSUE TITLE
NoSuchMethodError: 'void net.minecraft.world.entity.ai.navigation.NavigationAbstract.o()'

### ISSUE THREAD

**Issue by mibby** [Arnuh/EchoPet#119]
Paper build 68 (Spigot 1.18.1)
EchoPets-Dev build 47

```
[15:37:41] [Server thread/ERROR]: Entity threw exception at spawn:1476.2989161256032,76.0,1775.367767717817
java.lang.NoSuchMethodError: 'void net.minecraft.world.entity.ai.navigation.NavigationAbstract.o()'
	at com.dsh105.echopet.compat.nms.v1_18_R1.entity.ai.PetGoalFollowOwner.finish(PetGoalFollowOwner.java:107) ~[EchoPet.jar:?]
	at com.dsh105.echopet.compat.api.ai.PetGoalSelector.updateGoals(PetGoalSelector.java:137) ~[EchoPet.jar:?]
	at com.dsh105.echopet.compat.nms.v1_18_R1.entity.EntityPet.k(EntityPet.java:387) ~[EchoPet.jar:?]
	at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1128) ~[?:?]
	at net.minecraft.world.level.Level.guardEntityTick(Level.java:970) ~[?:?]
	at net.minecraft.server.level.ServerLevel.lambda$tick$5(ServerLevel.java:670) ~[?:?]
	at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:43) ~[paper-1.18.1.jar:git-Paper-68]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:650) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1607) ~[paper-1.18.1.jar:git-Paper-68]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:480) ~[paper-1.18.1.jar:git-Paper-68]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1470) ~[paper-1.18.1.jar:git-Paper-68]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.18.1.jar:git-Paper-68]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-68]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by mibby** [comment]
Seems to be fixed, thanks.
