### ISSUE TITLE
NoSuchFieldException: yamlOptions

### ISSUE THREAD

**Issue by mibby** [Arnuh/EchoPet#120]
Purpur dev 1492 (Paper 1.18.1)
EchoPets dev 48

Did spigot or something deprecate this in a recent commit? I noticed some other plugins making changes to their configuration code handling due to spigot changes.

```
[23:03:02] [Server thread/INFO]: [EchoPet] Enabling EchoPet v1.1.0-SNAPSHOT-b48
[23:03:02] [Server thread/ERROR]: Adding duplicate key 'ResourceKey[minecraft:sensor_type / minecraft:nearest_living_entities]' to registry
[23:03:02] [Server thread/ERROR]: Adding duplicate key 'ResourceKey[minecraft:sensor_type / minecraft:nearest_adult]' to registry
[23:03:02] [Server thread/WARN]: java.lang.NoSuchFieldException: yamlOptions
[23:03:02] [Server thread/WARN]: 	at java.base/java.lang.Class.getDeclaredField(Class.java:2610)
[23:03:02] [Server thread/WARN]: 	at EchoPet.jar//com.dsh105.echopet.compat.api.config.YAMLConfig.<clinit>(YAMLConfig.java:40)
[23:03:02] [Server thread/WARN]: 	at EchoPet.jar//com.dsh105.echopet.compat.api.config.YAMLConfigManager.getNewConfig(YAMLConfigManager.java:54)
[23:03:02] [Server thread/WARN]: 	at EchoPet.jar//com.dsh105.echopet.EchoPetPlugin.loadConfiguration(EchoPetPlugin.java:178)
[23:03:02] [Server thread/WARN]: 	at EchoPet.jar//com.dsh105.echopet.EchoPetPlugin.onEnable(EchoPetPlugin.java:123)
[23:03:02] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[23:03:02] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[23:03:02] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[23:03:02] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:564)
[23:03:02] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:478)
[23:03:02] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:321)
[23:03:02] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1218)
[23:03:02] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322)
[23:03:02] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by mibby** [comment]
@Arnuh i.e. https://github.com/Rosewood-Development/PlayerParticles/commit/1c0dd516e2630149eee10e7ba875bae65c7e45d2

**Comment by Arnuh** [comment]
I'm still having consistent buildtools issues since 1.18 started. I can never fully understand what fixes it but I usually give up if I can't in a couple tries.

I do plan to reinstall my OS in a week or so which might fix it.

Does look like it just got renamed to `yamlDumperOptions` tho so I can probably fix it without testing.

**Comment by mibby** [comment]
Great, I'd be happy to test as soon as it's pushed.

**Comment by mibby** [comment]
Seems fixed, thanks! Just the duplicate key registry issue left with 1.18.
