### ISSUE TITLE
Error loading pet data - Cannot invoke "String.equalsIgnoreCase(String)" because "input" is null

### ISSUE THREAD

**Issue by andrewkm** [Arnuh/EchoPet#152]
Paper 1.20.4 Build 388

I frequently get this when certain players log in.
Any idea what could be going on here and how I should go about it?
```
[22:24:19] [Server thread/ERROR]: [EchoPet] Error loading pet data for ece8950c-4b0b-4b7a-bcf8-0d828c416a80
java.lang.NullPointerException: Cannot invoke "String.equalsIgnoreCase(String)" because "input" is null
	at com.dsh105.echopet.compat.api.entity.data.PetDataParser$BooleanParser.parse(PetDataParser.java:51) ~[EchoPet.jar:?]
	at com.dsh105.echopet.compat.api.entity.data.PetDataParser$BooleanParser.parse(PetDataParser.java:43) ~[EchoPet.jar:?]
	at com.dsh105.echopet.api.FileStorageManager.createRider(FileStorageManager.java:219) ~[EchoPet.jar:?]
	at com.dsh105.echopet.api.FileStorageManager.create(FileStorageManager.java:189) ~[EchoPet.jar:?]
	at com.dsh105.echopet.api.FileStorageManager.lambda$load$4(FileStorageManager.java:149) ~[EchoPet.jar:?]
	at com.dsh105.echopet.compat.api.plugin.action.SyncBukkitAction.lambda$execute$0(SyncBukkitAction.java:59) ~[EchoPet.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.4.jar:git-Paper-388]
	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[paper-1.20.4.jar:git-Paper-388]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1633) ~[paper-1.20.4.jar:git-Paper-388]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.20.4.jar:git-Paper-388]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1512) ~[paper-1.20.4.jar:git-Paper-388]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214) ~[paper-1.20.4.jar:git-Paper-388]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[paper-1.20.4.jar:git-Paper-388]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
```
Pets.yml entry:
```
  ece8950c-4b0b-4b7a-bcf8-0d828c416a80:
    pet:
      type: SKELETONHORSE
      name: FuriuosGeorge's Skeleton Horse
      data:
        saddle: true
    rider:
      type: CAT
      name: FuriuosGeorge's Cat
      data:
        sit: true
        tamed: true
        light_gray: true
```

**Comment by andrewkm** [comment]
Thank you! <3
