### ISSUE TITLE
Caused by: java.lang.IllegalArgumentException: Can't find attribute minecraft:generic.flying_speed (b130)

### ISSUE THREAD

**Issue by Techirion** [Arnuh/EchoPet#156]
On latest dev build on latest Paper 1.21

```
com.destroystokyo.paper.exception.ServerInternalException: Entity threw exception at bskyblock_world:7.050769805456204,86.8965005307149,-1020.9866284341435
	at net.minecraft.world.level.Level.guardEntityTick(Level.java:1645)
	at net.minecraft.server.level.ServerLevel.lambda$tick$7(ServerLevel.java:790)
	at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:39)
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:761)
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1813)
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:478)
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1605)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1310)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:331)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.IllegalArgumentException: Can't find attribute minecraft:generic.flying_speed
	at net.minecraft.world.entity.ai.attributes.AttributeSupplier.getAttributeInstance(AttributeSupplier.java:20)
	at net.minecraft.world.entity.ai.attributes.AttributeSupplier.getValue(AttributeSupplier.java:27)
	at net.minecraft.world.entity.ai.attributes.AttributeMap.getValue(AttributeMap.java:66)
	at net.minecraft.world.entity.LivingEntity.getAttributeValue(LivingEntity.java:2759)
	at net.minecraft.world.entity.ai.control.FlyingMoveControl.tick(FlyingMoveControl.java:38)
	at EchoPet.jar//com.dsh105.echopet.compat.nms.v1_21.entity.ai.BiMoveControl.tick(BiMoveControl.java:63)
	at net.minecraft.world.entity.Mob.serverAiStep(Mob.java:950)
	at net.minecraft.world.entity.LivingEntity.aiStep(LivingEntity.java:3582)
	at net.minecraft.world.entity.Mob.aiStep(Mob.java:678)
	at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:3279)
	at net.minecraft.world.entity.Mob.tick(Mob.java:445)
	at EchoPet.jar//com.dsh105.echopet.compat.nms.v1_21.entity.EntityPet.tick(EntityPet.java:345)
	at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1301)
	at net.minecraft.world.level.Level.guardEntityTick(Level.java:1639)
	... 9 more
```

It seems like I can reproduce it with flying pets, by flying up in the air and then ejecting (using shift for example), it doesn't happen with all mobs tho...

For example, I wasn't able to reproduce with Bee, Allay pet, but could reproduce with Phantom, Blaze, ...

**Comment by Techirion** [comment]
The same exception is also spamming console on b128 on 1.20.6

**Comment by Techirion** [comment]
Further update, at the moment on latest Paper 1.21 it seems like it's being thrown a bit less, was still able to replicate with Phantom by riding Phantom pet a bit then dismounting (while being in the air)


Think adding

```
	@Override
	public void tick(){
		try {
			get().tick();
		} catch (IllegalArgumentException e) {
			// ignored ? Issue #156
		}
	}
```

to BiMoveControl would fix the issue, just not sure if that's the right way to go about it...

**Comment by Techirion** [comment]
```
	public static void setFlyingSpeed(LivingEntity entity, float flyingSpeed){
		if(entity.getAttribute(Attributes.FLYING_SPEED) == null)
			entity.getAttributes().registerAttribute(Attributes.FLYING_SPEED);

		entity.getAttribute(Attributes.FLYING_SPEED).setBaseValue(flyingSpeed);
	}
```
in nms\v1_21\src\main\java\com\dsh105\echopet\nms\VersionBreaking.java ? Would prob be better solution...
