### ISSUE TITLE
EnderDragon on 1.13.2 causes NPE.

### ISSUE THREAD

**Issue by andrewkm** [Arnuh/EchoPet#30]
https://pastebin.com/raw/EKRjb4fK

**Comment by Arnuh** [comment]
#24 
Was planning to fix it a couple days ago but some elmaker repo from I assume worldguard slowed down maven builds by 30-50 seconds so I just left that project for another day.

**Comment by mibby** [comment]
@Arnuh The error still occurs with the latest source compiled unfortunately.

```
[03:51:10] [Server thread/WARN]: [EchoPet] Task #144740 for EchoPet v1.0.4-SNAPSHOT-b generated an exception
java.lang.IllegalStateException: Failed to create EntityPet object for player
	at com.dsh105.echopet.compat.api.registration.PetRegistrationEntry.createEntityPet(PetRegistrationEntry.java:90) ~[?:?]
	at com.dsh105.echopet.compat.api.entity.PetType.getNewEntityPetInstance(PetType.java:202) ~[?:?]
	at com.dsh105.echopet.compat.nms.v1_13_R2.SpawnUtil.spawn(SpawnUtil.java:54) ~[?:?]
	at com.dsh105.echopet.api.pet.Pet.spawnPet(Pet.java:91) ~[?:?]
	at com.dsh105.echopet.listeners.PetOwnerListener$2.run(PetOwnerListener.java:237) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:63) ~[patched_1.13.2.jar:git-Paper-432]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[patched_1.13.2.jar:git-Paper-432]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1008) ~[patched_1.13.2.jar:git-Paper-432]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-432]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.2.jar:git-Paper-432]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.2.jar:git-Paper-432]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
	at com.dsh105.echopet.compat.api.registration.PetRegistrationEntry.createEntityPet(PetRegistrationEntry.java:86) ~[?:?]
	... 11 more
Caused by: java.lang.NullPointerException
	at com.dsh105.echopet.compat.nms.v1_13_R2.entity.type.EntityEnderDragonPet.n(EntityEnderDragonPet.java:182) ~[?:?]
	at net.minecraft.server.v1_13_R2.EntityInsentient.<init>(EntityInsentient.java:70) ~[patched_1.13.2.jar:git-Paper-432]
	at net.minecraft.server.v1_13_R2.EntityCreature.<init>(EntityCreature.java:15) ~[patched_1.13.2.jar:git-Paper-432]
	at com.dsh105.echopet.compat.nms.v1_13_R2.entity.EntityPet.<init>(EntityPet.java:64) ~[?:?]
	at com.dsh105.echopet.compat.nms.v1_13_R2.entity.EntityNoClipPet.<init>(EntityNoClipPet.java:32) ~[?:?]
	at com.dsh105.echopet.compat.nms.v1_13_R2.entity.type.EntityEnderDragonPet.<init>(EntityEnderDragonPet.java:61) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
	at com.dsh105.echopet.compat.api.registration.PetRegistrationEntry.createEntityPet(PetRegistrationEntry.java:86) ~[?:?]
	... 11 more
```
