### ISSUE TITLE
WorldEdit vector implementation logic changed.

### ISSUE THREAD

**Issue by mibby** [Arnuh/EchoPet#31]
New WorldEdit dev builds added a new vector implementation. Logic is now Vector3/BlockVector3.

```
[21:00:50] [Server thread/WARN]: [EchoPet] Task #663 for EchoPet v1.0.4-SNAPSHOT-b generated an exception
java.lang.NoClassDefFoundError: com/sk89q/worldedit/Vector
	at com.dsh105.echopet.compat.api.util.WorldUtil.allowRegion(WorldUtil.java:54) ~[?:?]
	at com.dsh105.echopet.compat.api.util.WorldUtil.allowPets(WorldUtil.java:37) ~[?:?]
	at com.dsh105.echopet.api.PetManager.createPet(PetManager.java:113) ~[?:?]
	at com.dsh105.echopet.api.PetManager.createPetFromFile(PetManager.java:242) ~[?:?]
	at com.dsh105.echopet.api.PetManager.loadPets(PetManager.java:77) ~[?:?]
	at com.dsh105.echopet.listeners.PetOwnerListener$2.run(PetOwnerListener.java:235) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:63) ~[patched_1.13.2.jar:git-Paper-429]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[patched_1.13.2.jar:git-Paper-429]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1008) ~[patched_1.13.2.jar:git-Paper-429]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-429]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.2.jar:git-Paper-429]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.2.jar:git-Paper-429]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldedit.Vector
	at java.net.URLClassLoader.findClass(URLClassLoader.java:471) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:158) ~[patched_1.13.2.jar:git-Paper-429]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104) ~[patched_1.13.2.jar:git-Paper-429]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	... 13 more

```
```
[21:25:48] [Server thread/WARN]: [EchoPet] Task #13031 for EchoPet v1.0.4-SNAPSHOT-b generated an exception
java.lang.NoClassDefFoundError: com/sk89q/worldedit/Vector
	at com.dsh105.echopet.compat.api.util.WorldUtil.allowRegion(WorldUtil.java:54) ~[?:?]
	at com.dsh105.echopet.compat.api.util.WorldUtil.allowPets(WorldUtil.java:37) ~[?:?]
	at com.dsh105.echopet.api.PetManager.createPet(PetManager.java:113) ~[?:?]
	at com.dsh105.echopet.api.PetManager.createPetFromFile(PetManager.java:242) ~[?:?]
	at com.dsh105.echopet.api.PetManager.loadPets(PetManager.java:77) ~[?:?]
	at com.dsh105.echopet.listeners.PetOwnerListener$2.run(PetOwnerListener.java:235) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:63) ~[patched_1.13.2.jar:git-Paper-429]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[patched_1.13.2.jar:git-Paper-429]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1008) ~[patched_1.13.2.jar:git-Paper-429]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-429]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.2.jar:git-Paper-429]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.2.jar:git-Paper-429]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```
```
[22:26:09] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'pet wolf' in com.dsh105.echopet.commands.util.DynamicPluginCommand(pet)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.13.2.jar:git-Paper-429]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:729) ~[patched_1.13.2.jar:git-Paper-429]
	at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1761) ~[patched_1.13.2.jar:git-Paper-429]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1565) ~[patched_1.13.2.jar:git-Paper-429]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.13.2.jar:git-Paper-429]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.13.2.jar:git-Paper-429]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:12) ~[patched_1.13.2.jar:git-Paper-429]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:109) ~[patched_1.13.2.jar:git-Paper-429]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1016) ~[patched_1.13.2.jar:git-Paper-429]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-429]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.2.jar:git-Paper-429]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.2.jar:git-Paper-429]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NoClassDefFoundError: com/sk89q/worldedit/Vector
	at com.dsh105.echopet.compat.api.util.WorldUtil.allowRegion(WorldUtil.java:54) ~[?:?]
	at com.dsh105.echopet.compat.api.util.WorldUtil.allowPets(WorldUtil.java:37) ~[?:?]
	at com.dsh105.echopet.api.PetManager.createPet(PetManager.java:113) ~[?:?]
	at com.dsh105.echopet.commands.PetCommand.onCommand(PetCommand.java:425) ~[?:?]
	at com.dsh105.echopet.commands.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:47) ~[?:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[patched_1.13.2.jar:git-Paper-429]
	... 14 more
```

**Comment by Arnuh** [comment]
wtf

**Comment by Arnuh** [comment]
@andrewkm you're free to jenkins this btw.. I don't have a jenkins setup because im waiting for the java11 support to be stable plus setting up building spigot, and the repo shit is a pain.

**Comment by mibby** [comment]
@Arnuh Does this actually utilize the new vector implementation? I can't seem to get it to compile.

**Comment by Arnuh** [comment]
I didn't actually test it but it worked fine with the latest jar grabbed from the repo.

**Comment by andrewkm** [comment]
@Arnuh Will look into this shortly and provide a jenkins :)

**Comment by andrewkm** [comment]
Going to reference an issue I just made btw, incase it has anything to do with @mibby saying he cannot compile:
https://github.com/Arnuh/EchoPet/issues/32

**Comment by andrewkm** [comment]
Done: 
https://github.com/Arnuh/EchoPet/issues/33

**Comment by andrewkm** [comment]
@mibby Same issue here, is yours the same:
https://ci.ecocitycraft.com/job/EchoPet/6/console
