### ISSUE TITLE
Echopet needs update for latest WE

### ISSUE THREAD

**Issue by andrewkm** [Arnuh/EchoPet#32]
WE changed it's vector system completely.
https://github.com/sk89q/WorldEdit/commit/399e0ad5fa7637d5d3ccce7ead1ad409e85c7dd2
Echopet needs an update to it.

`[18:40:51] [Server thread/WARN]: [EchoPet] Task #2083751 for EchoPet v1.0.4-SNAPSHOT-b generated an exception
java.lang.NoClassDefFoundError: com/sk89q/worldedit/Vector
	at com.dsh105.echopet.compat.api.util.WorldUtil.allowRegion(WorldUtil.java:54) ~[?:?]
	at com.dsh105.echopet.compat.api.util.WorldUtil.allowPets(WorldUtil.java:37) ~[?:?]
	at com.dsh105.echopet.api.PetManager.createPet(PetManager.java:113) ~[?:?]
	at com.dsh105.echopet.api.SqlPetManager.createPetFromDatabase(SqlPetManager.java:135) ~[?:?]
	at com.dsh105.echopet.api.SqlPetManager.createPetFromDatabase(SqlPetManager.java:101) ~[?:?]
	at com.dsh105.echopet.api.PetManager.loadPets(PetManager.java:56) ~[?:?]
	at com.dsh105.echopet.listeners.PetOwnerListener$2.run(PetOwnerListener.java:235) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:63) ~[patched_1.13.2.jar:git-Paper-447]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[patched_1.13.2.jar:git-Paper-447]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1008) ~[patched_1.13.2.jar:git-Paper-447]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-447]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.2.jar:git-Paper-447]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.2.jar:git-Paper-447]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_192]`

**Comment by andrewkm** [comment]
I'm an idiot, just saw your commits.
