### ISSUE TITLE
NoSuchMethodError: com.sk89q.worldguard.internal.platform.WorldGuardPlatform.getWorldByName(Ljava/lang/String;)Lcom/sk89q/worldedit/world/World; 	

### ISSUE THREAD

**Issue by mibby** [Arnuh/EchoPet#38]
Paper dev 488 (Spigot 1.13.2)
EchoPet dev 19
WorldEdit dev 3982
WorldGuard dev 1779

@Arnuh Incompatibile with latest WorldGuard?

```
[00:50:43] [Server thread/INFO]: player issued server command: /pet tropicalfish
[00:50:43] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'pet tropicalfish' in com.dsh105.echopet.commands.util.DynamicPluginCommand(pet)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.13.2.jar:git-Paper-488]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:732) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1792) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1595) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:12) ~[patched_1.13.2.jar:git-Paper-488]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:109) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1016) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.2.jar:git-Paper-488]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NoSuchMethodError: com.sk89q.worldguard.internal.platform.WorldGuardPlatform.getWorldByName(Ljava/lang/String;)Lcom/sk89q/worldedit/world/World;
	at com.dsh105.echopet.compat.api.util.WorldUtil.allowRegion(WorldUtil.java:49) ~[?:?]
	at com.dsh105.echopet.compat.api.util.WorldUtil.allowPets(WorldUtil.java:37) ~[?:?]
	at com.dsh105.echopet.api.PetManager.createPet(PetManager.java:113) ~[?:?]
	at com.dsh105.echopet.commands.PetCommand.onCommand(PetCommand.java:425) ~[?:?]
	at com.dsh105.echopet.commands.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:47) ~[?:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[patched_1.13.2.jar:git-Paper-488]
	... 14 more
```

```
[00:50:54] [Server thread/INFO]: player issued server command: /pet squid
[00:50:54] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'pet squid' in com.dsh105.echopet.commands.util.DynamicPluginCommand(pet)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.13.2.jar:git-Paper-488]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:732) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1792) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1595) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:12) ~[patched_1.13.2.jar:git-Paper-488]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:109) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1016) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.2.jar:git-Paper-488]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NoSuchMethodError: com.sk89q.worldguard.internal.platform.WorldGuardPlatform.getWorldByName(Ljava/lang/String;)Lcom/sk89q/worldedit/world/World;
	at com.dsh105.echopet.compat.api.util.WorldUtil.allowRegion(WorldUtil.java:49) ~[?:?]
	at com.dsh105.echopet.compat.api.util.WorldUtil.allowPets(WorldUtil.java:37) ~[?:?]
	at com.dsh105.echopet.api.PetManager.createPet(PetManager.java:113) ~[?:?]
	at com.dsh105.echopet.commands.PetCommand.onCommand(PetCommand.java:425) ~[?:?]
	at com.dsh105.echopet.commands.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:47) ~[?:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[patched_1.13.2.jar:git-Paper-488]
	... 14 more
```

**Comment by mibby** [comment]
Caused by this commit I believe.
https://github.com/sk89q/WorldGuard/commit/fdd9064170af7b67d180ee642faaa91fff82be88#diff-1e315883962e0c03911551be57487653

**Comment by Arnuh** [comment]
Guess so.. Looks like I just use the bukkit adapter instead.. No need to use that junk anyway unless im supporting 2 different apis like worldguard.
