### ISSUE TITLE
1.11.2 load issue

### ISSUE THREAD

**Issue by TUCAOEVER** [Arnuh/EchoPet#44]
[18:14:46] [Server thread/ERROR]: Could not load 'plugins\EchoPet-1.0.4-SNAPSHOT.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: com/dsh105/echopet/compat/api/plugin/IEchoPetPlugin
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[1.11.2.jar:git-Paper-1104]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:331) ~[1.11.2.jar:git-Paper-1104]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:254) [1.11.2.jar:git-Paper-1104]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.loadPlugins(CraftServer.java:302) [1.11.2.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:208) [1.11.2.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:612) [1.11.2.jar:git-Paper-1104]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
Caused by: java.lang.NoClassDefFoundError: com/dsh105/echopet/compat/api/plugin/IEchoPetPlugin
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_181]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_181]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_181]
	at java.net.URLClassLoader.defineClass(Unknown Source) ~[?:1.8.0_181]
	at java.net.URLClassLoader.access$100(Unknown Source) ~[?:1.8.0_181]
	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_181]
	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_181]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_181]
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_181]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102) ~[1.11.2.jar:git-Paper-1104]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[1.11.2.jar:git-Paper-1104]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_181]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_181]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:65) ~[1.11.2.jar:git-Paper-1104]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:127) ~[1.11.2.jar:git-Paper-1104]
	... 6 more
Caused by: java.lang.ClassNotFoundException: com.dsh105.echopet.compat.api.plugin.IEchoPetPlugin
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_181]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102) ~[1.11.2.jar:git-Paper-1104]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[1.11.2.jar:git-Paper-1104]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_181]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_181]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_181]
	at java.net.URLClassLoader.defineClass(Unknown Source) ~[?:1.8.0_181]
	at java.net.URLClassLoader.access$100(Unknown Source) ~[?:1.8.0_181]
	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_181]
	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_181]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_181]
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_181]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102) ~[1.11.2.jar:git-Paper-1104]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[1.11.2.jar:git-Paper-1104]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_181]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_181]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:65) ~[1.11.2.jar:git-Paper-1104]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:127) ~[1.11.2.jar:git-Paper-1104]
	... 6 more
[18:14:46] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[18:14:46] [Server thread/INFO]: **** Beginning UUID conversion, this may take A LONG time ****

**Comment by Arnuh** [comment]
Looks like the jar failed to compile properly or you're not using the fat jar with all depends added.

Either way I don't support pre 1.13 anymore due to Material changes(Deleted the release since it might of mislead people).
