### ISSUE TITLE
NoSuchMethodError: com.dsh105.echopet.compat.nms.v1_14_R1.entity.EntityPet.ax()Z [

### ISSUE THREAD

**Issue by mibby** [Arnuh/EchoPet#49]
Paper dev 122 (Spigot 1.14.3)
EchoPets 1.14 dev 9

```
[16:10:22] [Server thread/WARN]: Entity threw exception at world:14273.289137623968,74.0,4161.846999860054
[16:10:22] [Server thread/WARN]: java.lang.NoSuchMethodError: com.dsh105.echopet.compat.nms.v1_14_R1.entity.EntityPet.ax()Z
[16:10:22] [Server thread/WARN]: 	at com.dsh105.echopet.compat.nms.v1_14_R1.entity.ai.PetGoalFloat.shouldStart(PetGoalFloat.java:47)
[16:10:22] [Server thread/WARN]: 	at com.dsh105.echopet.compat.api.ai.PetGoalSelector.updateGoals(PetGoalSelector.java:142)
[16:10:22] [Server thread/WARN]: 	at com.dsh105.echopet.compat.nms.v1_14_R1.entity.EntityPet.tick(EntityPet.java:550)
[16:10:22] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.WorldServer.entityJoinedWorld(WorldServer.java:579)
[16:10:22] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.World.a(World.java:933)
[16:10:22] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:354)
[16:10:22] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1192)
[16:10:22] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:420)
[16:10:22] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1064)
[16:10:22] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:908)
[16:10:22] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[16:10:22] [Server thread/ERROR]: [global] TIMING_STACK_CORRUPTION - Report this to Paper! This is a potential bug in Paper (TimingIdentifier{id=Minecraft:## tickEntity - com.dsh105.echopet.compat.nms.v1_14_R1.entity.type.EntityOcelotPet} did not stopTiming)
java.lang.Throwable: null
	at co.aikar.timings.TimingHandler.popTimingStack(TimingHandler.java:135) ~[patched_1.14.3.jar:git-Paper-122]
	at co.aikar.timings.TimingHandler.stopTiming(TimingHandler.java:117) ~[patched_1.14.3.jar:git-Paper-122]
	at net.minecraft.server.v1_14_R1.World.a(World.java:945) ~[patched_1.14.3.jar:git-Paper-122]
	at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:354) ~[patched_1.14.3.jar:git-Paper-122]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1192) ~[patched_1.14.3.jar:git-Paper-122]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:420) ~[patched_1.14.3.jar:git-Paper-122]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1064) ~[patched_1.14.3.jar:git-Paper-122]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:908) ~[patched_1.14.3.jar:git-Paper-122]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

**Comment by Arnuh** [comment]
Requires @andrewkm to update his jenkins to build 1.14.3 spigot.

Also andrew you should be able to get latest changes without having a delay of hours with a plugin, idk what plugin I use on my personal jenkins but I setup a webhook for `https://ci.ecocitycraft.com/github-webhook/` for you which is all mine does(no credentials)

**Comment by andrewkm** [comment]
@Arnuh updated:
https://ci.ecocitycraft.com/job/EchoPet%201.14/

As well, I can set the delay lower than 3 hours, but due to having over 100+ projects on the jenkins (privated) I can't poll that often. If you'd like me to use the webhook and poll automatically, you'll have to enter the secret webhook text that I provide you, this is how our jenkins is set up on our end.

It would be setup via application/json as such: https://i.imgur.com/nj0K161.png

**Comment by andrewkm** [comment]
Although @Arnuh I did just make a small change, see if that will trigger a build for you without a webhook secret.
