### ISSUE TITLE
1.14.4 incompatibility - NoSuchMethodError EnumCreatureType

### ISSUE THREAD

**Issue by mibby** [Arnuh/EchoPet#50]
Paper dev 136 (spigot 1.14.4)
EchoPet dev 17

@Arnuh Fix needed similar to what was done in HolographicDisplays? https://github.com/filoghost/HolographicDisplays/commit/467fe7493e0f572eed366ef727553d1597aba893 
```
[09:28:32] [Server thread/WARN]: [EchoPet] Task #90284 for EchoPet v1.0.5-SNAPSHOT-b17 generated an exception
java.lang.NoSuchMethodError: net.minecraft.server.v1_14_R1.EntityTypes.d()Lnet/minecraft/server/v1_14_R1/EnumCreatureType;
	at com.dsh105.echopet.compat.nms.v1_14_R1.PetRegistry.enablePets(PetRegistry.java:101) ~[?:?]
	at com.dsh105.echopet.compat.nms.v1_14_R1.SpawnUtil.spawn(SpawnUtil.java:53) ~[?:?]
	at com.dsh105.echopet.api.pet.Pet.spawnPet(Pet.java:97) ~[?:?]
	at com.dsh105.echopet.listeners.PetOwnerListener$2.run(PetOwnerListener.java:237) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-136]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.14.4.jar:git-Paper-136]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1144) ~[patched_1.14.4.jar:git-Paper-136]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:420) ~[patched_1.14.4.jar:git-Paper-136]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1076) ~[patched_1.14.4.jar:git-Paper-136]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:920) ~[patched_1.14.4.jar:git-Paper-136]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

**Comment by Arnuh** [comment]
Should work fine? I didn't do too much testing.
