### ISSUE TITLE
Enderdragon pet is broken.

### ISSUE THREAD

**Issue by mibby** [Arnuh/EchoPet#7]
Compiled as of commit https://github.com/Borlea/EchoPet/commit/9ffe50f8e22b0ebd98bb6d1a5a3f7933ad878322
Paper dev 1140 (Spigot 1.12)

The enderdragon pet just falls through the ground until it vanishes.

**Comment by Arnuh** [comment]
Might as well state this, i'm probably never going to fix this. Someone is fully open to PR a fix.

**Comment by andrewkm** [comment]
Can confirm. Tested all pets as of latest build and reported here:
https://github.com/Arnuh/EchoPet/issues/37

Riding enderdragons however is great and players definitely enjoy that :)

**Comment by mibby** [comment]
Paper dev 488 (Spigot 1.13.2)
EchoPet dev 19

@andrewkm @Arnuh Enderdragon pet unfortunately just errors for me.

```
[06:50:52] [Server thread/INFO]: mibby issued server command: /pet enderdragon
[06:50:52] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'pet enderdragon' in com.dsh105.echopet.commands.util.DynamicPluginCommand(pet)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.13.2.jar:git-Paper-488]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:732) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1792) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1595) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:12) ~[patched_1.13.2.jar:git-Paper-488]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:109) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1016) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.2.jar:git-Paper-488]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.IllegalStateException: Failed to create EntityPet object for mibby
	at com.dsh105.echopet.compat.api.registration.PetRegistrationEntry.createEntityPet(PetRegistrationEntry.java:90) ~[?:?]
	at com.dsh105.echopet.compat.api.entity.PetType.getNewEntityPetInstance(PetType.java:202) ~[?:?]
	at com.dsh105.echopet.compat.nms.v1_13_R2.SpawnUtil.spawn(SpawnUtil.java:54) ~[?:?]
	at com.dsh105.echopet.api.pet.Pet.spawnPet(Pet.java:91) ~[?:?]
	at com.dsh105.echopet.commands.PetCommand.onCommand(PetCommand.java:442) ~[?:?]
	at com.dsh105.echopet.commands.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:47) ~[?:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[patched_1.13.2.jar:git-Paper-488]
	... 14 more
Caused by: java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
	at com.dsh105.echopet.compat.api.registration.PetRegistrationEntry.createEntityPet(PetRegistrationEntry.java:86) ~[?:?]
	at com.dsh105.echopet.compat.api.entity.PetType.getNewEntityPetInstance(PetType.java:202) ~[?:?]
	at com.dsh105.echopet.compat.nms.v1_13_R2.SpawnUtil.spawn(SpawnUtil.java:54) ~[?:?]
	at com.dsh105.echopet.api.pet.Pet.spawnPet(Pet.java:91) ~[?:?]
	at com.dsh105.echopet.commands.PetCommand.onCommand(PetCommand.java:442) ~[?:?]
	at com.dsh105.echopet.commands.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:47) ~[?:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[patched_1.13.2.jar:git-Paper-488]
	... 14 more
Caused by: java.lang.NoSuchFieldError: k
	at com.dsh105.echopet.compat.nms.v1_13_R2.entity.type.EntityEnderDragonPet.initDatawatcher(EntityEnderDragonPet.java:70) ~[?:?]
	at com.dsh105.echopet.compat.nms.v1_13_R2.entity.EntityPet.x_(EntityPet.java:521) ~[?:?]
	at net.minecraft.server.v1_13_R2.Entity.<init>(Entity.java:235) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.EntityLiving.<init>(EntityLiving.java:147) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.EntityInsentient.<init>(EntityInsentient.java:53) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.EntityCreature.<init>(EntityCreature.java:15) ~[patched_1.13.2.jar:git-Paper-488]
	at com.dsh105.echopet.compat.nms.v1_13_R2.entity.EntityPet.<init>(EntityPet.java:64) ~[?:?]
	at com.dsh105.echopet.compat.nms.v1_13_R2.entity.EntityNoClipPet.<init>(EntityNoClipPet.java:32) ~[?:?]
	at com.dsh105.echopet.compat.nms.v1_13_R2.entity.type.EntityEnderDragonPet.<init>(EntityEnderDragonPet.java:61) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
	at com.dsh105.echopet.compat.api.registration.PetRegistrationEntry.createEntityPet(PetRegistrationEntry.java:86) ~[?:?]
	at com.dsh105.echopet.compat.api.entity.PetType.getNewEntityPetInstance(PetType.java:202) ~[?:?]
	at com.dsh105.echopet.compat.nms.v1_13_R2.SpawnUtil.spawn(SpawnUtil.java:54) ~[?:?]
	at com.dsh105.echopet.api.pet.Pet.spawnPet(Pet.java:91) ~[?:?]
	at com.dsh105.echopet.commands.PetCommand.onCommand(PetCommand.java:442) ~[?:?]
	at com.dsh105.echopet.commands.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:47) ~[?:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[patched_1.13.2.jar:git-Paper-488]
	... 14 more
```

**Comment by andrewkm** [comment]
No errors here, just falls through the world and doesn’t work right that’s all.

This will likely never be fixed.

**Comment by mibby** [comment]
Might be an nms rename change with latest spigot.

**Comment by andrewkm** [comment]
You’re welcome to PR a fix.

**Comment by Arnuh** [comment]
This has existed since 1.13.2 came out. I just never fixed it because no one complained.

**Comment by andrewkm** [comment]
@arnuh is it possible to fix :P ?
Would be cool if it was one day fixed. Enderdragons sure were fun to mess with.

**Comment by Arnuh** [comment]
Oops forgot to mention issues again. https://github.com/Arnuh/EchoPet/commit/3fe13518ffb8269636145cc41614586c1c71178f
Should work for the dragon now..

I still dunno when I want to spend time to fix the actual bugs the dragon has.

**Comment by mibby** [comment]
@Arnuh This needs to be updated for 1.13.2.
https://github.com/Arnuh/EchoPet/blob/master/modules/v1_13_R2/src/com/dsh105/echopet/compat/nms/v1_13_R2/entity/EntityAgeablePet.java#L75

Line 75 and 76. k to movementTick

**Comment by Arnuh** [comment]
I think it should be inactive tick from what I saw in mojangs ageable.

**Comment by mibby** [comment]
@Arnuh I was comparing it with the EntityAgeable patch change on Spigot here.

Before: https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/browse/nms-patches/EntityAgeable.patch?until=421c1728c81e2f729dff88da2ac96535d2b8e5e8&untilPath=nms-patches%2FEntityAgeable.patch

After: https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/browse/nms-patches/EntityAgeable.patch?until=c64fe5080c996e8ea29b3e113043dd0aa962aaee&untilPath=nms-patches%2FEntityAgeable.patch

But if inactive is the correct one, 👍

**Comment by Arnuh** [comment]
They renamed inactive tick earlier(I think) and is higher up in the class.
