### ISSUE TITLE
Java 16 - NoSuchFieldException: modifiers

### ISSUE THREAD

**Issue by mibby** [Arnuh/EchoPet#85]
```
[14:12:04] [Server thread/INFO]: [EchoPet] Enabling EchoPet v1.0.8-SNAPSHOT-b12
[14:12:04] [Server thread/WARN]: java.lang.NoSuchFieldException: modifiers
[14:12:04] [Server thread/WARN]: 	at java.base/java.lang.Class.getDeclaredField(Class.java:2549)
[14:12:04] [Server thread/WARN]: 	at com.dsh105.echopet.compat.api.reflection.FieldUtil.setFinalStatic(FieldUtil.java:15)
[14:12:04] [Server thread/WARN]: 	at com.dsh105.echopet.compat.nms.v1_16_R3.NMSEntityUtil.doVillagerFix(NMSEntityUtil.java:210)
[14:12:04] [Server thread/WARN]: 	at com.dsh105.echopet.compat.nms.v1_16_R3.PetRegistry.<init>(PetRegistry.java:56)
[14:12:04] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[14:12:04] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78)
[14:12:04] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[14:12:04] [Server thread/WARN]: 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[14:12:04] [Server thread/WARN]: 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[14:12:04] [Server thread/WARN]: 	at com.dsh105.echopet.compat.api.reflection.SafeConstructor.newInstance(SafeConstructor.java:57)
[14:12:04] [Server thread/WARN]: 	at com.dsh105.echopet.EchoPetPlugin.onEnable(EchoPetPlugin.java:123)
[14:12:04] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[14:12:04] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[14:12:04] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[14:12:04] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518)
[14:12:04] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432)
[14:12:04] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:282)
[14:12:04] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074)
[14:12:04] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:293)
[14:12:04] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
```

**Comment by Arnuh** [comment]
Hmm this complicates things if support for older versions wants to be kept considering 1.16 use to not even run on JDK 16 until recently. I think since no one really runs "modern" old versions of Minecraft I can just axe them whenever Minecraft changes its java version dependency.

Other then that, this fix is somewhat simple I think
