### ISSUE TITLE
Rabbit Error when walking

### ISSUE THREAD

**Issue by Waterman1001** [Arnuh/EchoPet#92]
#### Description

When spawning the Rabbit Pet and walking with it, I get an error in the console and the Rabbit gets despawned.
If I just stand still, there is no problem, so it has to do with the walking I suppose.

#### Error
The error I receive in the Console is the following:

```bash
[12:49:55 INFO]: waterman1001 issued server command: /pet rabbit
[12:49:59 ERROR]: Entity threw exception at Spawn:-1069.1819173468082,4.0,2093.0311310693096
java.lang.NoSuchMethodError: 'net.minecraft.world.level.pathfinder.PathEntity net.minecraft.world.entity.ai.navigation.NavigationAbstract.k()'
        at com.dsh105.echopet.compat.nms.v1_17_R1.entity.type.EntityRabbitPet.mobTick(EntityRabbitPet.java:104) ~[?:?]
        at net.minecraft.world.entity.Mob.serverAiStep(Mob.java:840) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.aiStep(LivingEntity.java:3148) ~[?:?]
        at net.minecraft.world.entity.Mob.aiStep(Mob.java:620) ~[?:?]
        at com.dsh105.echopet.compat.nms.v1_17_R1.entity.type.EntityRabbitPet.movementTick(EntityRabbitPet.java:151) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:2874) ~[?:?]
        at net.minecraft.world.entity.Mob.tick(Mob.java:388) ~[?:?]
        at com.dsh105.echopet.compat.nms.v1_17_R1.entity.EntityPet.tick(EntityPet.java:402) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:942) ~[?:?]
        at net.minecraft.world.level.Level.guardEntityTick(Level.java:864) ~[?:?]
        at net.minecraft.server.level.ServerLevel.lambda$tick$5(ServerLevel.java:639) ~[?:?]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:54) ~[patched_1.17.jar:git-Paper-71]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:620) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1551) ~[patched_1.17.jar:git-Paper-71]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:477) ~[patched_1.17.jar:git-Paper-71]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1404) ~[patched_1.17.jar:git-Paper-71]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1180) ~[patched_1.17.jar:git-Paper-71]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[patched_1.17.jar:git-Paper-71]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```

#### Version
I am running Paper version git-Paper-71 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)

**Comment by Arnuh** [comment]
This is probably a wontfix.. I'm not going to handle paper having incorrect mappings while it works fine on spigot.

I'll probably have to get some info about how paper plans to handle issues like this.

**Comment by Arnuh** [comment]
Looks like this specific mapping error is already documented here https://github.com/PaperMC/paperweight/issues/24

**Comment by andrewkm** [comment]
Experiencing same thing here, hopefully paper gets this one eventually.

**Comment by Arnuh** [comment]
Looks to be fixed as of paper build 360. Make sure to update to the latest paper everyone.

**Comment by andrewkm** [comment]
@Arnuh you fucking cute man. I shall test new paperweight soon.
